### ISSUE TITLE
Cant start server KeyError: 'steps'

### ISSUE THREAD

**Issue by vaughnlfisher** [craftbeerpi/craftbeerpi4#81]
Hi
Since updating recently just cant get the server to start. It keeps failing with the same error. See below.

START
2021-07-19:15:30:05,324 INFO     [craftbeerpi.py:86] Init CraftBeerPI
2021-07-19:15:30:05,441 INFO     [eventbus.py:56] Topic #
2021-07-19:15:30:05,873 INFO     [craftbeerpi.py:240] 
  _____            __ _   ____                 _____ _ 
 / ____|          / _| | |  _ \               |  __ (_)
| |     _ __ __ _| |_| |_| |_) | ___  ___ _ __| |__) | 
| |    | '__/ _` |  _| __|  _ < / _ \/ _ \ '__|  ___/ |
| |____| | | (_| | | | |_| |_) |  __/  __/ |  | |   | |
 \_____|_|  \__,_|_|  \__|____/ \___|\___|_|  |_|   |_|
                                                       
                                                       
 _  _    ___   ___   ____  _  _    
| || |  / _ \ / _ \ |___ \| || |   
| || |_| | | | | | |  __) | || |_  
|__   _| | | | | | | |__ <|__   _| 
   | |_| |_| | |_| | ___) |  | |   
   |_(_)\___(_)___(_)____/   |_|   
                                   
                                   

2021-07-19:15:30:05,873 INFO     [craftbeerpi.py:241] www.CraftBeerPi.com
2021-07-19:15:30:05,873 INFO     [craftbeerpi.py:242] (c) 2021 Manuel Fritsch
2021-07-19:15:30:05,878 INFO     [plugin_controller.py:30] Trying to load plugin gpioactor
2021-07-19:15:30:05,891 INFO     [plugin_controller.py:30] Trying to load plugin mqtt_sensor
2021-07-19:15:30:05,894 INFO     [plugin_controller.py:30] Trying to load plugin hysteresis
2021-07-19:15:30:05,897 INFO     [plugin_controller.py:30] Trying to load plugin dummysensor
2021-07-19:15:30:05,900 INFO     [plugin_controller.py:30] Trying to load plugin mashstep
2021-07-19:15:30:05,974 INFO     [plugin_controller.py:30] Trying to load plugin onewire
2021-07-19:15:30:06,16 INFO     [plugin_controller.py:30] Trying to load plugin dummyactor
2021-07-19:15:30:06,26 INFO     [plugin_controller.py:30] Trying to load plugin httpsensor
2021-07-19:15:30:06,35 INFO     [plugin_controller.py:52] Try to load plugin:  cbpi4ui 
2021-07-19:15:30:06,39 INFO     [plugin_controller.py:56] Plugin cbpi4ui loaded successfully
2021-07-19:15:30:06,39 INFO     [plugin_controller.py:52] Try to load plugin:  lcd_screen 
2021-07-19:15:30:06,41 ERROR    [plugin_controller.py:58] FAILED to load plugin lcd_screen 
2021-07-19:15:30:06,41 ERROR    [plugin_controller.py:59] No module named 'lcd_screen'
2021-07-19:15:30:06,42 INFO     [basic_controller2.py:36] SensorController Load 
2021-07-19:15:30:06,42 INFO     [basic_controller2.py:45] SensorController Starting 
2021-07-19:15:30:06,43 INFO     [basic_controller2.py:87] SensorController Start Id VhTKyss7sNkUpkmt9nyQo7 
2021-07-19:15:30:06,44 INFO     [basic_controller2.py:103] SensorController started VhTKyss7sNkUpkmt9nyQo7
2021-07-19:15:30:06,45 INFO     [step_controller.py:29] INIT STEP Controller
2021-07-19:15:30:06,48 ERROR    [base_events.py:1608] unhandled exception during asyncio.run() shutdown
task: <Task finished coro=<_run_app() done, defined at /usr/local/lib/python3.7/dist-packages/aiohttp/web.py:287> exception=KeyError('steps')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web.py", line 508, in run_app
    loop.run_until_complete(main_task)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web.py", line 307, in _run_app
    app = await app  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/cbpi/craftbeerpi.py", line 270, in init_serivces
    await self.step.init()
  File "/usr/local/lib/python3.7/dist-packages/cbpi/controller/step_controller.py", line 30, in init
    self.load(startActive=True)
  File "/usr/local/lib/python3.7/dist-packages/cbpi/controller/step_controller.py", line 63, in load
    self.profile = data["steps"]
KeyError: 'steps'
Traceback (most recent call last):
  File "/usr/local/bin/cbpi", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/cbpi/cli.py", line 251, in start
    cbpi.start()
  File "/usr/local/lib/python3.7/dist-packages/cbpi/craftbeerpi.py", line 283, in start
    web.run_app(self.init_serivces(), port=self.static_config.get("port", 2202))
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web.py", line 508, in run_app
    loop.run_until_complete(main_task)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web.py", line 307, in _run_app
    app = await app  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/cbpi/craftbeerpi.py", line 270, in init_serivces
    await self.step.init()
  File "/usr/local/lib/python3.7/dist-packages/cbpi/controller/step_controller.py", line 30, in init
    self.load(startActive=True)
  File "/usr/local/lib/python3.7/dist-packages/cbpi/controller/step_controller.py", line 63, in load
    self.profile = data["steps"]
KeyError: 'steps'

**Comment by avollkopf** [comment]
Did you try to remove the step_data.json file? Ther could be a conflict. Otherwise you should try to remove the config flder and run cbpi setup again.

**Comment by vaughnlfisher** [comment]
Thanks for the tip where is that stored?

**Comment by avollkopf** [comment]
> 
> 
> Thanks for the tip where is that stored?

In the folder where you installed it. There is a folder called config. Typically it is in /home/pi if you installed everything on a pi.

**Comment by avollkopf** [comment]
No issues with most recent version detected.
